#pragma once

#include "../include/utils.hpp"

#include <unordered_map>
#include <unordered_set>

// Don't forget to add to tokenNameLookup
enum class TokenType {
    identifier,
    keyword,
    intLiteral,
    floatLiteral,
    string,
    stringBegin,
    stringMiddle,
    stringEnd,
    plus,
    minus,
    asterisk,
    slash,
    exponent,
    root,
    equal,
    notEqual,
    doubleEqual,
    less,
    lessEqual,
    more,
    moreEqual,
    comma,
    semicolon,
    colon,
    dot,
    exclamation,
    doubleAmpersand,
    ampersand,
    bar,
    doubleBar,
    parenStart,
    parenEnd,
    curlyStart,
    curlyEnd,
    squareStart,
    squareEnd,
    quote,
    doubleQuote,
    backTick,
    ifKeyword,
    elseKeyword,
    elifKeyword,
    forKeyword,
    doKeyword,
    fnKeyword,
    trueKeyword,
    falseKeyword,
    typeKeyword,
    newline,
    tab,
    carriageReturn,
    escapeQuote,
    escapeDoubleQuote,
    escapeFormatStart,
    escapeFormatEnd,
    indent,
    dedent,
    eof,
    notKeyword,
    andKeyword,
    orKeyword,
    inKeyword,
    isKeyword,
};

static std::unordered_map<TokenType, std::string> tokenTypeNameLookup = {
    { TokenType::identifier, "identifier" },
    { TokenType::keyword, "keyword" },
    { TokenType::intLiteral, "intLiteral" },
    { TokenType::floatLiteral, "floatLiteral" },
    { TokenType::string, "string" },
    { TokenType::stringBegin, "stringBegin" },
    { TokenType::stringMiddle, "stringMiddle" },
    { TokenType::stringEnd, "stringEnd" },
    { TokenType::plus, "plus" },
    { TokenType::minus, "minus" },
    { TokenType::asterisk, "asterisk" },
    { TokenType::slash, "slash" },
    { TokenType::exponent, "exponent" },
    { TokenType::root, "root" },
    { TokenType::equal, "equal" },
    { TokenType::notEqual, "notEqual" },
    { TokenType::doubleEqual, "doubleEqual" },
    { TokenType::less, "less" },
    { TokenType::lessEqual, "lessEqual" },
    { TokenType::more, "more" },
    { TokenType::moreEqual, "moreEqual" },
    { TokenType::comma, "comma" },
    { TokenType::semicolon, "semicolon" },
    { TokenType::colon, "colon" },
    { TokenType::dot, "dot" },
    { TokenType::exclamation, "exclamation" },
    { TokenType::doubleAmpersand, "doubleAmpersand" },
    { TokenType::ampersand, "ampersand" },
    { TokenType::bar, "bar" },
    { TokenType::doubleBar, "doubleBar" },
    { TokenType::parenStart, "parenStart" },
    { TokenType::parenEnd, "parenEnd" },
    { TokenType::curlyStart, "curlyStart" },
    { TokenType::curlyEnd, "curlyEnd" },
    { TokenType::squareStart, "squareStart" },
    { TokenType::squareEnd, "squareEnd" },
    { TokenType::quote, "quote" },
    { TokenType::doubleQuote, "doubleQuote" },
    { TokenType::backTick, "backTick" },
    { TokenType::ifKeyword, "ifKeyword" },
    { TokenType::forKeyword, "forKeyword" },
    { TokenType::doKeyword, "doKeyword" },
    { TokenType::fnKeyword, "fnKeyword" },
    { TokenType::newline, "newline" },
    { TokenType::tab, "tab" },
    { TokenType::carriageReturn, "carriageReturn" },
    { TokenType::escapeQuote, "escapeQuote" },
    { TokenType::escapeDoubleQuote, "escapeDoubleQuote" },
    { TokenType::escapeFormatStart, "escapeFormatStart" },
    { TokenType::escapeFormatEnd, "escapeFormatEnd" },
    { TokenType::indent, "indent" },
    { TokenType::dedent, "dedent" },
    { TokenType::eof, "eof" },
    { TokenType::notKeyword, "notKeyword" },
    { TokenType::andKeyword, "andKeyword" },
    { TokenType::orKeyword, "orKeyword" },
    { TokenType::inKeyword, "inKeyword" },
    { TokenType::isKeyword, "isKeyword" },
};

struct Token {
    int line_num;
    int column_num;
    std::string text;
    TokenType type;
};

static const std::string& getTokenTypeName(TokenType tt){
    return tokenTypeNameLookup[tt];
}